# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-24 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
