# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_delete_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_principale',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, width_field='width_field'),
        ),
    ]
