# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-17 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_image_principale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_principale',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width_field',
        ),
    ]
